config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :recipes do
    member do
      get 'log'
      patch 'updatelog'
    end
  end

  resources :diaries
  resources :diets
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:index, :show, :edit, :update]
  resources :entries
  resources :journals, only: [:index]
  resources :stats, only: [:index]
  resources :food_groups

    get "journals/:year/:month/:day" => "journals#index",
      :constraints => { :month => /\d{1,2}/, :day => /\d{1,2}/, :year => /\d{4}/ },
      :as => "journal_date"

    get "stats/:year/:month/:day" => "stats#index",
      :constraints => { :month => /\d{1,2}/, :day => /\d{1,2}/, :year => /\d{4}/ },
      :as => "stat_date"

  root 'journals#index'

    resources :users do
      resources :diets, :entries, :journals
    end

end

app/models/recipe.rb
require 'open-uri'

class Recipe < ActiveRecord::Base
  has_many :nutritional_values
  has_many :food_groups, :through => :nutritional_values
  validate :check_url

  before_save :mark_nv_for_removal

def mark_nv_for_removal
  nutritional_values.each do |nv|
    nv.mark_for_destruction if nv.quantity.blank?
  end
end

def self.search(search)
  where("lower(name) LIKE ? OR lower(description) LIKE ?", "%#{search.downcase}%", "%#{search.downcase}%")
end

  accepts_nested_attributes_for :nutritional_values, allow_destroy: true, :reject_if => :reject_nv

  def reject_nv(attributes)
    if attributes[:quantity].blank?
      if attributes[:id].present?
        attributes.merge!({:_destroy => 1}) && false
      else
        true
      end
    end
  end

  def check_url
    if self.web_page && !self.web_page.empty?
      self.web_page = /^http/i.match(self.web_page) ? self.web_page : "http://#{self.web_page}"
      begin
        resp = URI.parse(self.web_page).kind_of?(URI::HTTP)
      rescue URI::InvalidURIError
        resp = false
      end
      errors.add(:web_page, "must be a valid Web Address") unless resp == true
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < BaseController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:search]
      @recipes = Recipe.search(params[:search]).order("name ASC")
    else
      @recipes = Recipe.all.order('name ASC')
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    food_groups = FoodGroup.all
    food_groups.each {|fg|
      @recipe.nutritional_values.build(:food_group_id => fg.id)
    }

  end

  # GET /recipes/1/edit
  def edit
    food_groups = FoodGroup.all
    food_groups.each {|fg|
      @recipe.nutritional_values.build(:food_group_id => fg.id) if !@recipe.nutritional_values.find_by(:food_group_id => fg.id)
    }
  end

  # GET /recipes/1/log
  def log
    set_recipe
  end

  # POST /recipes/1/updatelog
  def updatelog
    set_recipe
    #TODO: Add records to the entries table for converted quantity of recipe components

    respond_to do |format|
      log_unit = params[:log][:unit]

      log_measure = Measurement.parse("#{params[:log][:quantity]} #{log_unit}")
      recipe_measure = Measurement.parse("#{@recipe.quantity} #{@recipe.unit}")
      multiplier = (log_measure / recipe_measure).convert_to(log_unit).quantity

      entry_details = {}
      @recipe.nutritional_values.each do |nv|
        new_qty = nv.quantity * multiplier
        _date = Date.new(params[:logdate][:year].to_i,params[:logdate][:month].to_i,params[:logdate][:day].to_i)
        entry_details[nv.food_group.name] = {:portion => new_qty, :food_group_id => nv.food_group.id, :description => @recipe.name, :date => _date, :user_id => current_user.id}
      end

      ActiveRecord::Base.transaction do
        entry_details.each do |name, values|
          e = Entry.create!(values)
          e.save
        end
      end

      response_message = "Recipe #{@recipe.name} was recorded for #{params[:log][:quantity]} #{params[:log][:unit]}."
      format.html { redirect_to recipes_url, notice: response_message }
    end
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @redirect_location = recipes_url
    super
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    @redirect_location = recipes_url
    @update_success = @recipe.update(recipe_params)
    super
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
      if @recipe.quantity && @recipe.unit
        user_measurement = "#{@recipe.quantity} #{@recipe.unit}"
        measurement = Measurement.parse(user_measurement)
        @recipe.quantity = measurement.quantity
        @recipe.unit = measurement.unit
        @conversions = [measurement.unit.to_s.gsub(/\./,'')]
        Measurement::Unit[measurement.unit].conversions.each { |cv|
          @conversions << cv
        }
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :web_page, :quantity, :unit, nutritional_values_attributes: [:id, :recipe_id, :food_group_id, :quantity])
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="formContainer">
  <%= form_for(@recipe) do |f| %>
    <% if @recipe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

        <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    
    <div class="row">
      <div class="col-6">
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description %>
        </div>
      </div>
      <div class="col-6">
        <div class="field">
          <%= f.label :web_page %><br>
          <%= f.text_field :web_page %>
        </div>
        <div class="field">
          <%= f.label :serving %><br>
          <%= f.text_field :quantity, {:style => 'width: 49%'} %>
          <%= f.text_field :unit, {:style => 'width: 49%'} %>
        </div>
      </div>
    </div>

    <div class="field">
      <h2>Nutritional Values</h2>
      <div class="row">
        <%= f.fields_for :nutritional_values do |value| %>
          <%= render "nutritional_values", :ff => value %>
        <% end %>
      </div>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/recipes/_nutritional_values.html.erb
<div id="nv-list">
  <div class="col-6">
    <%= ff.label ff.object.food_group.name %>
    <%= ff.hidden_field :food_group_id, :value => ff.object.food_group.id %>
    <%= ff.text_field :quantity %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<div class="row">
<%= form_tag(recipes_path, :method => "get", id: "search-form") do %>
  <div class="col-7">
    <%= text_field_tag :search, params[:search], placeholder: "Search Recipes" %>
  </div>
  <div class="col-5">
    <%= submit_tag "Search" %>
  </div>
<% end %>
</div>

<% if !(@recipes.present?) %>
  <p>There are no recipes containing the term(s) <%= params[:search] %>.</p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Web page</th>
      <th>Quantity</th>
      <th>Unit</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr class="recipe">
        <td class="name"><%= highlight(recipe.name, params[:search]) %></td>
        <td class="description">
            <%= (params[:search] && !params[:search].empty?) ? highlight(excerpt(recipe.description, params[:search]), params[:search]) : recipe.description %>
        </td>
        <td class="url round-button">
          <% if !recipe.web_page.empty? %>
            <%= link_to('<i class="fa fa-link"></i>'.html_safe, recipe.web_page) %>
          <% end %>
        </td>
        <td class="quantity"><%= recipe.quantity %></td>
        <td class="unit"><%= recipe.unit %></td>
        <td class="round-button">
          <%= link_to '<i class="fa fa-book"></i>'.html_safe, log_recipe_path(recipe) %>
        </td>
        <td class="round-button">
          <%= link_to '<i class="fa fa-eye"></i>'.html_safe, recipe %>
        </td>
        <td class="round-button">
          <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_recipe_path(recipe) %>
        </td>
        <td class="round-button">
          <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/log.html.erb
<h1>Consumed <%= @recipe.name %></h1>
<div class="formContainer">
  <%= form_for(@recipe, url: {action: "updatelog"}) do |f| %>
    <div class="row">
      <div class="col-2 col-m-6">
        <label>Amount</label><br />
        <%= text_field(:log, :quantity) %>
      </div>
      <div class="col-2 col-m-6">
        <br />
        <%=
          select("log", "unit", @conversions.collect {|name, value| [name, name]})
        %>
      </div>
      <div class="col-8">
        <label>Date</label><br />
        <%= select_date Date.today, prefix: 'logdate', :with_css_classes => true %>
      </div>
    </div>

    <div class="actions">
      <%= submit_tag "Log Recipe" %>
    </div>

  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Web page:</strong>
  <%= @recipe.web_page %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @recipe.quantity %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @recipe.unit %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>