config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :recipes do
    member do
      get 'log'
      patch 'updatelog'
    end
  end

  resources :diaries
  resources :diets
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:index, :show, :edit, :update]
  resources :entries
  resources :journals, only: [:index]
  resources :stats, only: [:index]
  resources :food_groups

    get "journals/:year/:month/:day" => "journals#index",
      :constraints => { :month => /\d{1,2}/, :day => /\d{1,2}/, :year => /\d{4}/ },
      :as => "journal_date"

    get "stats/:year/:month/:day" => "stats#index",
      :constraints => { :month => /\d{1,2}/, :day => /\d{1,2}/, :year => /\d{4}/ },
      :as => "stat_date"

  root 'journals#index'

    resources :users do
      resources :diets, :entries, :journals
    end

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    if current_user
      @journal_date = params[:year] ? Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i) : Date.today
      yesterday = @journal_date -1
      tomorrow = @journal_date +1
      @_yesterday = {:year => yesterday.year, :month => yesterday.month, :day => yesterday.day}
      @_tomorrow = {:year => tomorrow.year, :month => tomorrow.month, :day => tomorrow.day} unless tomorrow > Time.zone.now.beginning_of_day

      # Multiple log entries per user per day
      @entries = Entry.by_day(@journal_date).where(:user_id => current_user.id)
      # One diary per user per day
      @diary = Diary.by_day(@journal_date).where(:user_id => current_user.id).first
      if !@diary && (@journal_date <= Time.zone.now.beginning_of_day)
        @diary = Diary.new
        @diary.date = @journal_date
      end

      session[:diary_return_to] = request.url
    end

  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.fetch(:journal, {})
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for(@journal) do |f| %>
  <% if @journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
      <% @journal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing Journal</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal %> |
<%= link_to 'Back', journals_path %>

app/views/journals/index.html.erb
<% if !user_signed_in? %>
  <%= link_to "Login", new_user_session_path  %>
  <%= link_to "Sign up", new_user_registration_path  %>
<% else %>
  <div class="row title-nav">
      <h1><%= @journal_date.strftime("%d %b %Y") %></h1>
      <div class="nav-button">
        <span class="tooltip"><%= link_to '<span class="tooltiptext">Previous Day</span><i class="fa fa-calendar-minus-o"></i>'.html_safe, journal_date_path(@_yesterday) %></span>
      </div>
      <div class="nav-button">
        <span class="tooltip"><%= link_to '<span class="tooltiptext">Today</span><i class="fa fa-calendar-check-o"></i>'.html_safe, journals_path %></span>
      </div>
      <div class="nav-button">
        <% if @_tomorrow %>
          <div class="tooltip"><%= link_to '<span class="tooltiptext">Next Day</span><i class="fa fa-calendar-plus-o"></i>'.html_safe, journal_date_path(@_tomorrow) %></div>
        <% else %>
          <div class="tooltip"><%= link_to '<span class="tooltiptext">At Current Day</span><i class="fa fa-ban"></i>'.html_safe, journals_path %></div>
        <% end %>
      </div>
  </div>

  <div class="row">
    <div class="col-6">
      <table>
        <thead>
          <tr>
            <th>Food group</th>
            <th>Portion</th>
            <th>Description</th>
            <th colspan="3">
            </th>
          </tr>
        </thead>

        <tbody>
          <% @entries.each do |entry| %>
            <tr>
              <td><%= entry.food_group.name %></td>
              <td><%= number_with_precision(entry.portion, :precision => 2) %></td>
              <td><%= entry.description %></td>
              <td class="round-button">
                <%= link_to '<i class="fa fa-eye"></i>'.html_safe, entry %>
              </td>
              <td class="round-button">
                <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_entry_path(entry) %>
              </td>
              <td class="round-button">
                <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, entry, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-6">
      <% current_user.daily_progress(@journal_date).each do |name, values| %>
        <%= render "big_button", :columns => 6, :title => name, :prompt =>"#{number_with_precision(values[:consumed], :precision =>2)} of #{number_with_precision(values[:target], :precision =>2)}", :entry_date => @journal_date %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <% if @diary %>
        <%= render partial: 'diaries/form', :locals => {:diary => @diary, :journal_date => @journal_date} %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/journals/new.html.erb
<h1>New Journal</h1>

<%= render 'form' %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_journal_path(@journal) %> |
<%= link_to 'Back', journals_path %>