config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  resources :recipes do
    member do
      get 'log'
      patch 'updatelog'
    end
  end

  resources :diaries
  resources :diets
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:index, :show, :edit, :update]
  resources :entries
  resources :journals, only: [:index]
  resources :stats, only: [:index]
  resources :food_groups

    get "journals/:year/:month/:day" => "journals#index",
      :constraints => { :month => /\d{1,2}/, :day => /\d{1,2}/, :year => /\d{4}/ },
      :as => "journal_date"

    get "stats/:year/:month/:day" => "stats#index",
      :constraints => { :month => /\d{1,2}/, :day => /\d{1,2}/, :year => /\d{4}/ },
      :as => "stat_date"

  root 'journals#index'

    resources :users do
      resources :diets, :entries, :journals
    end

end

app/models/diet.rb
class Diet < ActiveRecord::Base
  belongs_to :user
  has_many :intakes
  has_many :food_groups, :through => :intakes

  accepts_nested_attributes_for :intakes

  validates :start_date, :end_date, :overlap => {:scope => "user_id"}

  before_save :mark_intake_for_removal

  def mark_intake_for_removal
    intakes.each do |intake|
      intake.mark_for_destruction if intake.quantity.blank?
    end
  end

end

app/controllers/diets_controller.rb
class DietsController < BaseController
  before_action :set_diet, only: [:show, :edit, :update, :destroy]

  # GET /diets
  # GET /diets.json
  def index
    # @diets = Diet.all
    @diets = Diet.where(:user_id => current_user.id)

  end

  # GET /diets/1
  # GET /diets/1.json
  def show
    @intakes = @diet.intakes
  end

  # GET /diets/new
  def new
    @diet = Diet.new
    food_groups = FoodGroup.all
    food_groups.each {|fg|
      @diet.intakes.build(:food_group_id => fg.id)
    }
  end

  # GET /diets/1/edit
  def edit
    food_groups = FoodGroup.all
    food_groups.each {|fg|
      @diet.intakes.build(:food_group_id => fg.id) if !@diet.intakes.find_by(:food_group_id => fg.id)
    }
  end

  # POST /diets
  # POST /diets.json
  def create
    @diet = Diet.new(diet_params)
    super
  end

  # PATCH/PUT /diets/1
  # PATCH/PUT /diets/1.json
  def update
    @update_success = @diet.update(diet_params)
    super
  end

  # DELETE /diets/1
  # DELETE /diets/1.json
  def destroy
    @diet.destroy
    respond_to do |format|
      format.html { redirect_to diets_url, notice: 'Diet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diet
      @diet = Diet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diet_params
      params.require(:diet).permit(:start_date, :end_date, :description, :user_id, intakes_attributes: [:id, :diet_id, :food_group_id, :quantity])
    end
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/views/diets/_form.html.erb
<div class="formContainer">
<%= form_for(@diet) do |f| %>
  <% if @diet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diet.errors.count, "error") %> prohibited this diet from being saved:</h2>

      <ul>
      <% @diet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date, :with_css_classes => true %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date, :with_css_classes => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <h2>Daily Allowances</h2>
    <%= f.fields_for :intakes do |intake_f| %>
      <%= render "intake_fields", :ff => intake_f %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
</div>

app/views/diets/_intake_fields.html.erb
  <div>
    <%= ff.label :food_group_id %><br>
    <%= ff.collection_select :food_group_id, FoodGroup.order(:name),:id,:name, include_blank: true %>

    <%= ff.label :quantity %>
    <%= ff.text_field :quantity %>
  </div>

app/views/diets/edit.html.erb
<h1>Editing Diet</h1>

<%= render 'form' %>

<%= link_to 'Show', @diet %> |
<%= link_to 'Back', diets_path %>

app/views/diets/index.html.erb
<h1>Listing Diets</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diets.each do |diet| %>
      <tr>
        <td><%= diet.start_date %></td>
        <td><%= diet.end_date %></td>
        <td><%= diet.description %></td>
        <td><%= diet.user.email %></td>
        <td><%= link_to 'Show', diet %></td>
        <td><%= link_to 'Edit', edit_diet_path(diet) %></td>
        <td><%= link_to 'Destroy', diet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diet', new_diet_path %>

app/views/diets/new.html.erb
<h1>New Diet</h1>

<%= render 'form' %>

<%= link_to 'Back', diets_path %>

app/views/diets/show.html.erb
<p>
  <strong>Start:</strong>
  <%= @diet.start_date %>
</p>

<p>
  <strong>End:</strong>
  <%= @diet.end_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @diet.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @diet.user.email %>
</p>

<p>
  <strong>Allowances:</strong><br />
  <% @diet.intakes.each do |intake| %>
    <strong><%= intake.food_group.name %></strong>
    <%= intake.quantity %>
    <br />
  <% end %>
</p>

<%= link_to 'Edit', edit_diet_path(@diet) %> |
<%= link_to 'Back', diets_path %>